name: ujian_kls2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  hexcolor: ^2.0.7
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  multiselect: ^0.0.4
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

assets:
    - assets/image/

